- developers/guides/explainers/wallets-explained.md
migrate article from solana.com/news
> docs(guide): wallet explained

- developers/guides/getstarted/introduction-to-durable-nonces.md
Based on this original guide: https://github.com/0xproflupin/solana-durable-nonces
@jacobcreech suggested to make a PR here: https://github.com/solana-developers/solana-cookbook/pull/534#issuecomment-1612135214
> guide for durable nonces

- content/workshops/ship-your-first-xnft.md
- content/workshops/solana-101.md
- contentlayer.config.ts
- src/pages/api/content/[[...slug]].ts
- src/pages/api/nav/[group].ts
- src/pages/api/overview.ts
- src/pages/api/paths/[group].ts
- src/pages/api/records/[group].ts
- src/types/index.ts
- Added some workshop api to support workshop pages on solana-com
> extended workshop apis

- .github/workflows/formatting.yml
- content/courses/solana-course/content/arbitrary-cpi.md
- content/courses/solana-course/content/closing-accounts.md
- content/courses/solana-course/content/reinitialization-attacks.md
- docs/learn/state-compression.md
- package.json
- src/pages/api/nav/[group].ts
- src/pages/api/overview.ts
- src/pages/api/paths/[group].ts
- added prettier scripts to package json
- added a workflow for formatting
> Workflow formatting

- docs/terminology.md
Per other Foundation / Labs communication. Brandon Echter confirmed this is the preferred term.
> refactor: add on-chain program

- content/guides/token-extensions/transfer-hook.md
> transfer hook guide fixes

- next-env.d.ts
- src/app/api/content/[...slug]/route.ts
- src/app/api/nav/[...group]/route.ts
- src/app/api/overview/[...slug]/route.ts
- src/app/api/paths/[...group]/route.ts
- src/app/api/records/[...group]/route.ts
- src/pages/api/[[...index]].ts
migrated the entire api to app router
> migrate api to app router

- content/guides/token-extensions/transfer-hook.md
- Added easy hello world example
- Added counter example
- Updated the wSol example to use the js helper functions
> Update transfer hook guide

- content/guides/token-extensions/transfer-hook.md
Reverts solana-foundation/developer-content#55
> Revert "Update transfer hook guide"

- content/guides/token-extensions/transfer-hook.md
Reverts solana-foundation/developer-content#62
> Revert "Revert "Update transfer hook guide""

- content/guides/token-extensions/metadata-pointer.md
> [typo] "allows" -> "allowed" in `metadata-pointer.md`

- content/guides/token-extensions/getting-started.md
- minor grammar fixes
- specify the address of the Token Program, and add link to docs for new program, to remove ambiguity
> refactor: minor grammar fixes

- docs/terminology.md
- add nakamoto coefficient to terminology
> docs: add nakamoto coefficient to terminology

- content/guides/getstarted/solana-token-airdrop-and-faucets.md
- content/guides/token-extensions/transfer-hook.md
- Added triton to faucet supported RPCs
- Added close buffer and close programs instructions to retrieve sol
- Added transfer hook usecases to transferhook guide
> Added close buffers and programs to devnet sol guide

- content/guides/getstarted/solana-token-airdrop-and-faucets.md
Made editorial changes to the faucet/airdrop guide for it to be displayed prettier on the solana website
> refactor: editorial changes

- .github/ISSUE_TEMPLATE/0-default.md
- .github/PULL_REQUEST_TEMPLATE.md
Add github issues and pull request templates
> feat: added github templates

- docs/terminology.md
And add 'token program' too, with definitions for both per Chase/Jacob discussion.
> add: 'token extensions program' to terminology

- content/guides/token-extensions/getting-started.md
Confidential transfer and perm delegate don't work together. Added to list of incompatible combinations
> Added conf tranf + perm delegate to incompatible list

- docs/more/exchange.md
Added priority fee info for exchanges
> add: exchange priority fee info

- content/guides/advanced/how-to-use-priority-fees.md
There isn't a guide on priority fees
add a guide on priority fees
> add: priority fee guide

- docs/more/exchange.md
The priority fees section of the "add solana to your exchange" could be reworded for better readability and discoverability. 
Also, there are code block issues and multiple "result" table of contents entries.
- reworded details around priority fees, including adding more internal links
- fixed the code blocks
- fixed the multiple "results" table of contents entries
> [docs] exchange details page 

- content/guides/advanced/how-to-use-priority-fees.md
> add: priority fee guide cta to third party

- docs/programs/examples.md
Spelling Error: "though" instead of "through"
Fixed the error. Corrected "real time" to "real-time"
Fixes #
---
> Spelling Error Fix examples.md

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .prettierignore
updated the issue and PR template with better formatting and a note for PRs
> GitHub templates

- docs/more/exchange.md
The details listed around CU usage and best practices in the exchange guide could be more clear.
- update the title
- clarified the CU details with a caution callout
- code snippet updates for clarification
> [docs] refactor: exchange details

- content/guides/advanced/index.md
- content/guides/getstarted/index.md
- content/guides/intro/index.md
- content/guides/javascript/index.md
- content/guides/rpc/index.md
- content/guides/solang/index.md
- content/guides/token-extensions/index.md
- src/app/api/content/[...slug]/route.ts
- src/types/index.ts
- src/utils/navItem.ts
There are no dynamic breadcrumbs for the content's frontend
Add dynamic breadcrumbs data to the api for the frontend to consume
> [api] add breadcrumbs

- content/guides/advanced/how-to-optimize-compute.md
- editorial changes
- made the guide featured
> [editorial] how-to-optimize-compute

- content/guides/advanced/how-to-optimize-compute.md
- docs/intro/wallets.md
- improved sections for the wallets intro
- added guide tags
> refactor: minor nits

- content/guides/token-extensions/getting-started.md
- added a link to the transfer hook guide
- added link to token extension youtube playlist
> [guides] added links

- content/guides/permissioned-environments/index.md
Initial Solana Permissioned Environment Guide
> add: initial spe guide

- content/guides/permissioned-environments/index.md
fixed a few typos, adjusted the seo title for a better thumbnail image, and added an internal link
> [guide] SPE typo fix

- docs/core/transactions/confirmation.md
- docs/rpc/index.mdx
Transaction expiration (specifically blockhash expiration) is unclear in the docs
- clarified the wording around how blockhash expiration works
- updated links to use the anza repo
- updated seo metadata for this doc
Fixes #168
> [docs] clarify blockhash expiration

- .github/label-actions.yml
- .github/workflows/label-actions.yml
Adding label based actions for this repo
> [ci] added label actions

- content/guides/getstarted/full-stack-solana-development.md
- updated internal links to use relative links
- added code block file names when relevant
- fixed broken command (and updated it's respective output)
Fixes #181
> [guide] fixes in the full stack guide

- README.md
- content/guides/advanced/how-to-use-priority-fees.md
- content/guides/getstarted/local-rust-hello-world.md
- content/guides/getstarted/setup-local-development.md
- content/guides/getstarted/solana-token-airdrop-and-faucets.md
- content/guides/token-extensions/getting-started.md
- content/guides/token-extensions/metadata-pointer.md
- contentlayer.config.ts
- docs/more/exchange.md
- docs/terminology.md
- src/types/index.ts
- src/utils/navItem.ts
- src/utils/records.ts
- refactors contentlayer record names
- simplified standard callouts to use markdown blockquotes
- updated some links for consistency
> Minor updates

- docs/economics/index.md
Moved economics page from intro to the economics section
> fix: Moved economics

- CONTRIBUTING.md
- README.md
There is no contributing document and guidelines.
Added one :)
Fixes #97
> Contributing document

- CONTRIBUTING.md
Minor grammarly bits. No other changes.
This is a deliberately boring PR, I just want to keep unrelated fixes out of my next PR which has more substance.
> Minor grammarly bits

- README.md
> Markdown fix in README.md

- content/guides/getstarted/rust-to-solana.md
there are broken images due to being incorrectly formatted
fixed the broken image links
> fix: broken images

- docs/core/accounts.md
There was a typo in the docs.
`modify it data` -> `modify its data`
> Fix a typo

- content/guides/games/getting-started-with-game-development.md
Flutter is categorized as using JavaScript in the Game SDKs table. 
Changed to Dart.
> Updated Flutter with correct language; Dart.

- content/guides/getstarted/setup-local-development.md
- content/guides/getstarted/solana-test-validator.md
> fix: fix dates

- content/guides/wallets/add-solana-wallet-adapter-to-nextjs.md
> [guides] fix typo in add-solana-wallet-adapter-to-nextjs.md

- content/guides/getstarted/cosmwasm-to-solana.md
Need content for Cosmos Devs 
Create a guide walking through converting a CosmWasm Smart Contract to a Solana Program 
Fixes #
> Cosmwasm to solana

- CONTRIBUTING.md
- README.md
- content/guides/dapps/journal.md
- content/guides/games/game-sdks.md
- content/guides/games/store-sol-in-pda.md
- content/guides/getstarted/full-stack-solana-development.md
- content/guides/getstarted/intro-to-anchor.md
- content/guides/getstarted/intro-to-native-rust.md
- content/guides/getstarted/solana-test-validator.md
- content/guides/intro/wallets-explained.md
- content/guides/solang/getting-started.md
- content/guides/token-extensions/metadata-pointer.md
- content/guides/wallets/add-solana-wallet-adapter-to-nextjs.md
- content/resources/info/spl.md
- content/resources/sdks/anchor.md
- content/resources/tooling/solana-playground.md
- docs/clients/javascript.md
- docs/core/programs.md
- docs/economics/staking/index.md
- docs/programs/debugging.md
- docs/programs/deploying.md
- docs/programs/faq.md
- docs/programs/lang-c.md
- docs/programs/lang-rust.md
- docs/programs/limitations.md
- docs/programs/overview.md
- docs/terminology.md
- src/components/HomeComponent.tsx
Just minor bits while I work on #222
> Minor: fix typos

- docs/advanced/actions.md
- added a Get Started section to the actions docs
- added clarifying info around CORS headers for the actions.json
> [docs] actions: getting started

- package.json
- src/app/api/content/[...slug]/route.ts
- src/utils/constants.ts
- src/utils/parsers.ts
crowdin translated content often breaks the site :/
added a text pre processor to fix issues that content may have, especially the output from crowdin
> feat: pre process content

- docs/advanced/actions.md
- added details and a link to the blinks inspector
Fixes #
> [docs] added blinks inspector

- src/utils/parsers.ts
the content pre-parser alters the text within code blocks, which it should not
update the pre-processor to ignore code block internal content
Note: to ultimately fix this on the solana-com website, a PR need to be made there two. But this PR must be merged and go live first
Related: https://github.com/solana-foundation/developer-content/issues/262
> fix: prevent altering content in code blocks

- content/guides/advanced/introduction-to-durable-nonces.md
nonce authority cannot be a pda since a pda could not actually sign
corrected the guide that states this
> [guide]nonce pda authority

- docs/intro/quick-start.md
- Add Steps component which converts h3 tags to numbered steps
- Remove numbering from h3 tag titles
> Update quickstart page with steps component

- CONTRIBUTING.md
- src/utils/constants.ts
- state the "links" guidelines in the contributing doc
- enable linked images to use the local url for testing newly added images
> [chore] contributing and links

- content/courses/onchain-development/anchor-pdas.md
- content/courses/onchain-development/intro-to-anchor.md
anchor-pdas.md was not in sync with latest code changes
Added the needed changes to the account struct, contexts and tests in order to make the markdown file aligned with the latest code changes
> Updated anchor-pdas to be in sync with latest code changes

- content/guides/getstarted/how-to-create-a-token.md
Fixes:
- Don't mention bootcamp in metadata
- Use the OPOS assets and metadata file
- Fix an inconsistency in the mnt... address
- Add devnet to Solscan link
Plus:
- Properly alphabetically sort storage services and make grammar consistent
- Add Jonas' advice regarding image size to the guide
> Creating a token minor fixes

- content/courses/mobile/solana-mobile-dApps-with-expo.md
- content/courses/onchain-development/anchor-cpi.md
- content/courses/onchain-development/anchor-pdas.md
- content/courses/onchain-development/intro-to-anchor.md
- docs/core/tokens.md
- fix a broken link
- correct `console` code blocks since the do not give syntax highlighting
> refactor: minor fixes

- docs/programs/testing.md
Document/Guide for testing solana programs using solana-bankrun
> added document for testing with nodejs

- content/guides/getstarted/local-rust-hello-world.md
- content/guides/getstarted/setup-local-development.md
- docs/programs/examples.md
While going through our hello world user tests some problems emerged. 
Some of these are tackled in this PR. For example adding a link to the solana web faucet, adding solutions for some pit falls  and updating everything to the newest versions. 
Also added a JS client to the hello world guide to be able to call the program in the end for a nice little success.
> Added hints, updated versions and added js client

- docs/intro/quick-start.md
No content change, just replace:
```
<details>
{<summary></summary>}
</details>
```
With Accordion component:
```
<Accordion>
<AccordionItem title="">
</AccordionItem>
</Accordion>
```
> Update quickstart page with Accordion component

- content/courses/intro-to-solana/intro-to-custom-onchain-programs.md
- Typo
- Fixing typo of "tramsactions" to "transactions"
Fixes #
- Fixing typo
> Fixing typo in intro-to-custom-onchain-programs.md

- content/guides/token-extensions/transfer-hook.md
There are many people asking how to derive a token account owner in a transfer hook.
This guide section explains this and there is also a new example showing how to do this.
> Add using account data in transfer hook example

- content/cookbook/transactions/index.md
- content/cookbook/transactions/offline-transactions.md
from: https://solanacookbook.com/references/offline-transactions.html#sign-transaction
to: https://solana.com/developers/cookbook/transactions/offline-transactions
> migrate offline transactions refs from cookbook

- docs/intro/quick-start/program-derived-address.md
Duplicate content in Quick Start - Program Derived Address
remove the duplicate content
Fixes #
> Remove duplicate content in Quick Start - Program Derived Address

- content/courses/tokens-and-nfts/token-program.md
Some of the example import for solana web3 were wrong
Some of the code example have wrong web3 import @solana/web3 instead of @solana/web3.js
Fixed imports
Fixes #
> Fix wrong web3 import in token-program.md

- content/courses/connecting-to-offchain-data/metadata.yml
- content/courses/mobile/metadata.yml
- content/courses/native-onchain-development/metadata.yml
- content/courses/state-compression/metadata.yml
- content/courses/tokens-and-nfts/metadata.yml
metaplex-foundation/js is:
- Deprecated, as of July 15
- Has a bunch of security issues
- Non functional due to recent Solana RPC changes
Hide until Superteam can fix.
> Hide outdated content using deprecated metaplex-foundation/js library

- docs/advanced/actions.md
updated the actions docs to include the new features that have been rolled out to the public:
- action chaining
- new input types
> [docs] actions - added docs for chaining and input types

- CONTRIBUTING.md
Add tabs and accordion code snippet to contributing.md as example of how to use the components on docs.
> Add tabs and accordion code snippet to contributing.md

- content/courses/native-onchain-development/deserialize-instruction-data.md
While doing the prettier for #309 (which Nick did anyway, thanks Nick) I did a quick grammarly and general English run for this lesson.
> Minor grammar fixes to deserialize instruction data

- content/guides/dapps/cash-app.md
- content/guides/dapps/journal.md
- content/guides/getstarted/full-stack-solana-development.md
- content/guides/getstarted/hello-world-in-your-browser.md
- content/guides/getstarted/local-rust-hello-world.md
- content/guides/getstarted/rust-to-solana.md
- content/guides/getstarted/scaffold-nextjs-anchor.md
- content/guides/getstarted/solana-test-validator.md
- content/guides/solang/getting-started.md
- content/guides/token-extensions/dynamic-meta-data-nft.md
- content/guides/token-extensions/getting-started.md
- docs/clients/rust.md
- docs/intro/dev.md
- docs/programs/lang-rust.md
- docs/programs/overview.md
- redirects.json
Update links from installation guide to installation page on docs
> Update links to installation page

- content/courses/tokens-and-nfts/token-program.md
> fixed Typo

- content/courses/onchain-development/local-setup.md
- Updated styling and grammar with content
- Updated additional issues and resolution
- Updated solana cli command content for solana test validator
Fixes #
> Onchain development - Updated local setup lesson

- content/courses/onchain-development/intro-to-onchain.md
- changes in title, objectives, and description
- made the summary and overview sections more elaborative and detailed
- PDA section improved
> onchain-development intro-to-onchain updated

- content/courses/connecting-to-offchain-data/verifiable-randomness-functions.md
- content/courses/native-onchain-development/serialize-instruction-data-frontend.md
incorrect url file path for /connecting-to-offchain-data/oracles
changed the file path for /connecting-to-offchain-data/oracles to the correct link.
> Update verifiable-randomness-functions and serialize-instruction-data-frontend

- content/guides/getstarted/full-stack-solana-development.md
- The current implementation uses a mix of .then() and async/await, leading to inconsistent code. 
- Additionally, error handling and logging are minimal, and the dependency array in useEffect does not include all relevant variables, which can lead to missed updates.
- Replaced .then() with async/await for consistency and improved readability.
- Added try/catch blocks to handle errors during account data fetching and decoding.
- Enhanced logging with clearer and more informative error messages to aid in debugging.
- Updated the dependency array to include counterPDA and connection, ensuring better reactivity and stability in the useEffect hook.
> full-stack-solana-development - refactor useEffect to improve async/await usage and error handling 

- content/courses/mobile/mwa-deep-dive.md
- The updateBalance function used .then() instead of await, leading to inconsistent async/await syntax.
- Error handling when fetching the balance was not using try/catch, making error logging less clear.
- Error variable names in logging were inconsistent, affecting code clarity.
- Replaced .then() with await for consistency with async/await syntax.
- Added try/catch block to handle and log errors when fetching the balance.
- Improved readability and robustness of the balance update function.
- Updated error logging to use a consistent error variable name instead of e for better clarity.
> mwa deep dive: Refactor functions and handle errors.

- content/courses/connecting-to-offchain-data/oracles.md
- content/courses/offline-transactions/durable-nonces.md
- content/courses/program-optimization/program-architecture.md
- content/courses/state-compression/compressed-nfts.md
- content/courses/state-compression/generalized-state-compression.md
- content/courses/token-extensions/group-member.md
- content/courses/token-extensions/token-extensions-metadata.md
- content/courses/token-extensions/transfer-hook.md
- content/guides/games/interact-with-tokens.md
- content/guides/getstarted/rust-to-solana.md
- content/guides/javascript/compressed-nfts.md
- content/guides/token-extensions/dynamic-meta-data-nft.md
- docs/advanced/actions.md
- docs/advanced/state-compression.md
- docs/clients/rust.md
- docs/core/tokens.md
- docs/economics/staking/stake-programming.md
- docs/terminology.md
Like online / offline (see notion if you work at Solana Foundation).
No other changes.
> Offchain and onchain are one word per Foundation style guide

- content/courses/onchain-development/anchor-pdas.md
- content/courses/program-security/pda-sharing.md
- Updated code snippets with the latest anchor version
- Fixed content with updated version changes
- Fixed grammar and styling
- Fixed as per guidelines
Fixes #
Unboxed PRs
Starter - https://github.com/solana-developers/pda-sharing/pull/1
Solution - https://github.com/solana-developers/pda-sharing/pull/2
> Program security - PDA sharing lesson updated

- MAINTAINERS.md
add info about crowdin troubleshooting
> [maintainers] add info about crowdin troubleshooting

- docs/intro/installation.md
the install page does not mention avm for installing anchor
- added details around installing anchor via avm
Fixes #436
> feat: added avm install

- docs/core/accounts.md
- docs/core/index.md
there is no core concepts "landing page" that makes for developers and educators to share a single point of entry into the solana programming model
added this page
> [docs] added page Core Concepts page

- content/courses/program-security/arbitrary-cpi.md
- Updated code snippets with the latest anchor version
- Fixed content,
- Fixed grammar and styling
- Fixed as per guidelines
Fixes #
Unboxed PRs
Starter - https://github.com/solana-developers/arbitrary-cpi/pull/1
Solution - https://github.com/solana-developers/arbitrary-cpi/pull/2
> Program security - Arbitrary CPI lesson updated

- docs/intro/installation.md
Typo
Fix the typo: `Ancor` to `Anchor`
Fixes #
> Fix `Anchor` typo

- CONTRIBUTING.md
Minor grammatical update for clarification
The sentence seemed unclear, due to the additional "be." Also, the next sentence seems to be a fragment.
Remove "be," and removed the "-ing" suffix from "Including" to avoid the sentence fragment issue. 
Fixes #
> Edit: grammar: CONTRIBUTING.md

- content/courses/token-extensions/transfer-fee.md
Comment incorrect. 50 bps != 5%
Fix comment
> fix basis points comment

- content/courses/solana-pay/solana-pay.md
There was a code snippet that no longer works and contains some grammatical errors
The code snippet has been updated, and the grammatical errors have been corrected. Also, [a pr](https://github.com/Unboxed-Software/solana-scavenger-hunt-app/pull/1) has been opened for the [related repository](https://github.com/Unboxed-Software/solana-scavenger-hunt-app)
> Update solana pay content

- content/courses/mobile/intro-to-solana-mobile.md
- docs/programs/anchor/index.md
- pages were removed and no redirects were setup
- a PR was merged with bad prettier formatting, causing the prettier test to fail
- added redirects
- run prettier
> Docs missing redirects

- content/courses/intro-to-solana/interact-with-wallets.md
The Wallet connect button didn't have the expected UI shown in the courses.
Added single import line to get the ui from wallet-adapter-react-ui to get the changes
> Added styles in interact-with-wallet.md for wallet ui

- docs/intro/quick-start/program-derived-address.md
> Fix typo in program-derived-address.md

- content/courses/intro-to-solana/interact-with-wallets.md
useMemo not imported and Balance in SOL was not displaying properly
added the import and fixed the balance in SOL issue
> fixing useMemo and balance in SOL

- content/guides/getstarted/full-stack-solana-development.md
Duplicate word and misspelling of 'thing'
Remove duplicate word and correct 'thing' spelling
Fixes #
> Fix prose errors in: full-stack-solana-development.md

- content/courses/intro-to-solana/intro-to-writing-data.md
Fix 1 broken link in [intro-to-writing-data.md](https://github.com/solana-foundation/developer-content/blob/main/content/courses/intro-to-solana/intro-to-writing-data.md)
Fixes #
> Fix broken link intro-to-writing-data.md

- content/courses/mobile/intro-to-solana-mobile.md
- Fixed broken links
- Fixed SOL capitalization (Contributing guidelines)
- Suggestion: Reorder the placement of 'secret keys vs private keys' to the Introduction instead of a later paragraph [Connecting to a Wallet] for better flow.
Fixes #
> Fix broken links in intro-to-solana-mobile.md

- content/guides/getstarted/local-rust-hello-world.md
Run prettier on file to fix linting error
> Prettier linting fix

- docs/advanced/lookup-tables.md
- docs/advanced/retry.md
- docs/clients/javascript-reference.md
- docs/clients/javascript.md
- docs/clients/rust.md
- docs/core/accounts.md
- docs/core/clusters.md
- docs/core/cpi.md
- docs/core/fees.md
- docs/core/index.md
- docs/core/pda.md
- docs/core/programs.md
- docs/core/tokens.md
- docs/core/transactions.md
- docs/intro/installation.md
- docs/intro/quick-start/cross-program-invocation.md
- docs/intro/quick-start/deploying-programs.md
- docs/intro/quick-start/index.md
- docs/intro/quick-start/program-derived-address.md
- docs/intro/quick-start/reading-from-network.md
- docs/intro/quick-start/writing-to-network.md
- docs/programs/anchor/index.md
Add and update page description frontmatter
> Add and update page descriptions

- content/cookbook/wallets/create-keypair.md
- added `Tabs` component
- added web3.js v2 snippet
> [cookbook] keypairs - added v2 snippet 

- content/courses/onchain-development/intro-to-anchor.md
> Fix: correct typo "tha" to "the"

- content/courses/program-optimization/program-architecture.md
Duplicate text found in the documentation, which could cause confusion or reduce readability.
Removed duplicate lines in the documentation to improve clarity and readability.
Fixes #
> Fix: eliminated repeated text in program-architecture.md

- content/cookbook/accounts/get-account-balance.md
v2 of web3js introduces lots of granularity via the modular subpackages
Added a note about the subpackages and where to learn more
> [cookbook] added web3js v2 note for subpackages

- content/cookbook/index.md
Added a table of contents to the cookbook, with each table containing the list of the pages in each of its respective sections, and the client code that is included in each of those cookbook pages. (i.e. web3js, rust, etc). 
This pull request was created for https://app.gib.work/bounties/e7194501-26e0-4fca-8c10-b56908465011 in an attempt to solve a bounty #627 . Payment for the bounty is immediately sent to the contributor after merge.
Fixes: #627
> [cookbook] update landing page

- content/cookbook/programs/create-pda.md
Line 131 
-- // Airdop to Payer
++// Airdrop to Payer
Spell Check on line 131
-- // Airdop to Payer
++// Airdrop to Payer
Fixes #
> Update create-pda.md for spell check

- content/cookbook/wallets/sign-message.md
> Update sign-message.md updated to include v2 example

- content/cookbook/wallets/restore-keypair.md
> Update restore-keypair.md to include v2 examples

- docs/intro/dev.md
> Update grammar on dev.md

- content/courses/connecting-to-offchain-data/verifiable-randomness-functions.md
> docs: link

- docs/programs/anchor/idl.md
IDL stands for Interface Definition Language
Fixes #
> Corrected IDL acronym

- content/guides/getstarted/local-rust-hello-world.md
- docs/toolkit/best-practices.md
- docs/toolkit/getting-started.md
- docs/toolkit/index.md
- docs/toolkit/local-validator.md
- docs/toolkit/projects/anchor-init.md
- docs/toolkit/projects/existing-project.md
- docs/toolkit/projects/mobile-app.md
- docs/toolkit/projects/overview.md
- docs/toolkit/projects/project-layout.md
- docs/toolkit/projects/solana-program.md
- docs/toolkit/projects/web-app.md
- docs/toolkit/test-suite/basics.md
- docs/toolkit/test-suite/code-coverage.md
- docs/toolkit/test-suite/fuzz-tester.md
- docs/toolkit/test-suite/js-test.md
- docs/toolkit/test-suite/rust-tests.md
- docs/toolkit/test-suite/security-scanner.md
- docs/toolkit/troubleshooting.md
Update toolkit with minor changes and SEO optimization
> Toolkit updates

- docs/toolkit/getting-started.md
- docs/toolkit/index.md
- docs/toolkit/test-suite/basics.md
clarify installation of the solana toolkit and mucho cli
> refactor: details about mucho install

- docs/toolkit/getting-started.md
"publish" is incorrect
change to proper tense
Fixes #
publish -> published
> Update getting-started.md | Fix typo
