developers/guides/getstarted/setup-local-development.md

No reason to exclude Windows users. These instructions work reliably for all Windows 10/11 users, I have used them to develop on Solana for more than a year.

feat: add instructions for Windows users

---

developers/courses/solana-course/content/cpi.md
developers/courses/solana-course/content/deserialize-custom-data.md
developers/courses/solana-course/content/deserialize-instruction-data.md
developers/courses/solana-course/content/pda.md
developers/courses/solana-course/content/program-state-management.md
developers/courses/solana-course/content/serialize-instruction-data.md
developers/courses/solana-course/content/solana-pay.md
developers/guides/explainers/wallets-explained.md
developers/guides/solang/solang-getting-started.md
developers/resources/sdks/anchor.md
developers/resources/tooling/solana-playground.md
docs/intro/overview.md
docs/intro/wallets.md
docs/terminology.md

- fix: a transaction must have at least one instruction
-  fix: minor grammar fixes
- feat: add definitions for base58, memo, major unit, minor unit, mint, mint account, token account, wallet address, wallet name.
- fix: use 'programs' or 'on chain programs' unless explicitly referring to other blockchains
-  fix: solana tools use 'secret key' so be consistent with that
- feat: add definitions for tx, ix and sx

Terminology

---

developers/guides/advanced/introduction-to-durable-nonces.md

blockhashes as well as nonces are 32byte hashed represented as 44 character (base58 encoded) strings

minor changes in wording

---

content/guides/getstarted/solana-token-airdrop-and-faucets.md

- Quick fix to update the QuickNode Faucet URL ([https://faucet.quicknode.com/solana/devnet](https://faucet.quicknode.com/solana/devnet)) on the [How to get Solana devnet SOL](https://solana.com/developers/guides/getstarted/solana-token-airdrop-and-faucets) page.

Update URL to QuickNode's Faucet

---

content/guides/getstarted/solana-token-airdrop-and-faucets.md

The link was missing. 
This is the related issue: https://github.com/solana-foundation/developer-content/issues/25

Added link to dev net faucet form

---

src/pages/api/content/[[...slug]].ts
src/types/index.ts
src/utils/navItem.ts

- adjusted the `NavItem` type to support an optional `altRoutes` array
- added a function to generate a flat map of nav items
- `/api/content/*` will now return a `next` and `prev` NavItem to denote adjacent records

feat: added next prev record support

---

content/guides/rpc/configure-solana-rpc-on-aws.md
content/guides/solang/getting-started.md

Added a page to Guides section about Solana nodes on AWS in support of the [new AWS Node Runners app for Solana](https://aws-samples.github.io/aws-blockchain-node-runners/docs/Blueprints/Solana).

Added Solana on AWS page to Guides

---

content/guides/javascript/compressed-nfts.md
docs/economics/staking/index.md
docs/intro/dev.md
docs/intro/transaction_fees.md
docs/more/exchange.md

This PR fixes the docs related typos from the following PRs on the solana mono repo:
- https://github.com/solana-labs/solana/pull/34385
- https://github.com/solana-labs/solana/pull/34386

[docs] fix: assorted typos

---

content/guides/javascript/compressed-nfts.md

https://github.com/solana-labs/solana/pull/34184 contains a fix for a link in the compressed NFTs page, but with the move of the repo the change must be made here instead.
Update to the correct link.
cc @metasal1

Update compressed-nfts docs link

---

docs/more/exchange.md

The exchange integration page calls out how to integrate SPL Token, but doesn't mention anything about Token-2022.
Give some basic information about Token-2022 so that exchanges can integrate it!
To reduce confusion, I removed references to SPL Token v2 and just called it SPL Token.

exchange: Add token-2022 info

---

content/guides/token-extensions/transfer-hook.md

Transfer Hook extension guide. Solana Playground links this [Anchor program](https://github.com/solana-developers/anchor-transfer-hook) for starter / solution code.

Transfer Hook extension guide

---

docs/rpc/http/simulateTransaction.mdx

After [#34313](https://github.com/solana-labs/solana/pull/34313), the RPC will support inner instructions as part of the response for `simulateTransaction` if the boolean parameter `innerInstructions` is provided as `true`. This change will go live with `1.18`.
This change adds this to the docs!

docs: add RPC simulate tx inner instructions

---

docs/rpc/http/getTransaction.mdx

As per [this issue on the monorepo](https://github.com/solana-labs/solana/issues/34664), this constraint needed to be added to `getTransaction`!
Closes https://github.com/solana-labs/solana/issues/34664

rpc: add commitment constraint

---

content/guides/getstarted/solana-token-airdrop-and-faucets.md

In order to spin up a testnet validator, validators need testnet SOL. The faucet is often overloaded, so adding a few web faucets to this list for others to find.
Full disclosure: I wrote testnetfaucet.org (the code is in a public github repo here: https://github.com/ferric-sol/testnetfaucet) to help folks on the Solana Tech discord

Add links to a few more testnet faucets

---

content/guides/getstarted/local-rust-hello-world.md

Some issues with the Rust local "Hello world" example have been
popping up, especially with the release of `1.18.0`.
This change adds a few notes on how to handle dependency issues
when walking through this tutorial for the first time.

add hello world troubleshooting tips

---

docs/terminology.md

Current terminology uses the same term for the function and the thing being processed, which does not make logical sense and causes difficulty when explaining Solana development ("the instructions process the instructions"). 
Anchor 0.29 uses 'handler' to describe instruction handlers (see the function names when you start a project with `--template=multiple`) and this seems like a fine way of distinguishing between instructions and (what we now call) instruction handlers.

docs: add 'instruction handler' and separate from 'instruction'

---

content/guides/getstarted/evm-to-svm.md

The [EVM to SVM](https://solana.com/developers/evm-to-svm) developer page is not displayed within the Developer guides.
Make the page listed

[guides] added evm to svm guide redirect

---

src/utils/navItem.ts

There is a bug with the "nav grouping" code that results in nav groups that should be nested to NOT be nested. Making them appear at the root nav level.
Corrected the grouping key separator to correctly nest nav groups

[api] fix: nav group nesting

---

content/guides/advanced/introduction-to-durable-nonces.md

there is no variable named `nonceKeypairs` but there is one named `nonceKeypair` singular, and it is not an array
Fixes #

doc(introduction-to-durable-nonces.md): fix typo in Create Nonce Account section

---

src/utils/navItem.ts

when getting for content records from the api, it does not correctly parse the route for href finding
fixed it

[api] href parser for content records

---

docs/rpc/http/getBalance.mdx
docs/rpc/http/getLatestBlockhash.mdx
docs/rpc/http/getMinimumBalanceForRentExemption.mdx
docs/rpc/http/getProgramAccounts.mdx
docs/rpc/http/getSignaturesForAddress.mdx
docs/rpc/http/getTransaction.mdx
docs/rpc/http/sendTransaction.mdx
docs/rpc/http/simulateTransaction.mdx

The RPC section of the docs do not fully sort alphabetically since they are assigned a manual sort order
removed the sort order to have them sort alphabetically

refactor: removed manual sort order

---

content/guides/advanced/stake-weighted-qos.md

There is a typo in the sample yaml config for `staked-nodes-overrides` that uses `stake_map` where it should be `staked_map_id`
See: https://github.com/anza-xyz/agave/blob/21b682188511b208cae16155acc258fd1da9db0f/validator/src/admin_rpc_service.rs#L478-L495
- corrected the yaml field to `staked_map_id`

[guide] typo in stake weighted QoS guide

---

src/app/api/content/[...slug]/route.ts

the "edit on github" buttons on locale specific pages use an invalid link due to contentlayer including the i18n locale prefix in `_raw.sourceFilePath` 
strip out the i18n prefix from the `record._raw` attributes since all github files are only in the base language of english (and therefore do not have this prefix)

[i18n] remove i18n prefixes on `record._raw`

---

content/guides/advanced/introduction-to-durable-nonces.md

the nonce guide code blocks sometimes do not correctly render the syntax highlighting due to capitalization 
- made lower case to fix
- reordered a section to make it flow better

[guides] nonce code blocks

---

docs/core/clusters.md

With the new markdown processor on solana.com, nested quote blocks result in nested Callouts.
removed the nesting

fix: removed nested quote block

---

content/guides/getstarted/full-stack-solana-development.md

The buffer accounts link on [this page](https://solana.com/developers/guides/getstarted/full-stack-solana-development) points to `docs/programs/deploying#state-accounts` instead of `/docs/programs/deploying#state-accounts` which results in a [404 page](https://solana.com/developers/guides/getstarted/docs/programs/deploying#state-accounts) on the solana.com website.
Fix this specific link to be relative to root.

Fix link's relative path

---

content/guides/advanced/how-to-request-optimal-compute.md

- Use getSimulationComputeUnits() from helpers library. This is the same code, but has unit tests, we can publish updates if we need fixing, users don't need to maintain their own copy, etc.
- Change language for syntax highlighting to TS - existing code was using JS for code with types.
- Tweak wording slightly to emphasize using the function rather than the RPC method the function calls.
- Run prettier

Use getSimulationComputeUnits() from helpers library

---

docs/economics/inflation/inflation_schedule.md

Typo in inflation schedule document
Fix typo in inflation schedule document
Fixes #
remove duplicate "we can"

Fixes: Typo in inflation_schedule.md 

---

docs/core/transactions/versions.md

In 'docs/core/transactions/versions.md' clicked "view an example of a v0 transaction on Solana Explorer" which under the More Resources shows Not Found
updated link to use versioned transaction that shows on the explorer
Fixes #151

[docs] versioned transaction example

---

content/guides/advanced/stake-weighted-qos.md

The stake weighted QoS guide is not clear on the PORT number that should be used by the RPC node when specifying `--rpc-send-transaction-tpu-peer`
Adds a few sentences to clarify how to identify the quic tpu port number based on the dynamic port range.
Fixes #

fix: clarify quic tpu port for peering

---

docs/core/transactions/confirmation.md

- corrected that actually 151 recent blockhashes are valid due to being 0-indexed
- clarified the wording around this

[docs] fix: corrected blockhash count

---

docs/advanced/confirmation.md
docs/advanced/versions.md
docs/core/fees.md

With the recent PR to update many docs pages, a few were deleted or relocated. We missed a few redirects.
added the missing redirects

[docs] fix: broken links

---

content/guides/token-extensions/required-memo.md

As pointed out at https://github.com/solana-labs/solana-program-library/issues/6655#issuecomment-2085980581, there's no information about the `@solana/spl-memo` library in the token-extensions docs.
Also include an example of creating the memo instruction using `@solana/spl-memo`.
Fixes #

token-extensions: Add @solana/spl-memo usage to transfer memo

---

docs/programs/examples.md

The last commit removing solang didn't make it in the PR anymore. So here is a new one.

Remove solang references

---

content/guides/dapps/journal.md
content/guides/token-extensions/reallocate.md
content/guides/token-extensions/transfer-hook.md

I've found some typos in the documentation.
- change `calcualte` to `calculate`
- change `Transactoin` to `Transaction`
- change `transfered` to `transferred`

[docs] typos in documentation

---

docs/clients/rust.md
docs/programs/index.md
docs/programs/lang-rust.md

The [Deploying Programs](https://solana.com/docs/programs#1-setup-your-development-environment) doc gives no clear link to the very applicable getting started guides to help get a person started
- added hello world callouts on the deploying programs, rust client, and rust lang docs
Fixes #206

[docs] deploying programs to point to hello world and local setup

---

content/guides/getstarted/how-to-create-a-token.md

As mentioned in the comments at https://solana.stackexchange.com/a/12273/84, it's not clear in the docs that `initialize-metadata` only works with Token Extensions.
Add more clarifying language around when it's possible to use the token metadata extension.
Fixes #

create-a-token: Clarify that token metadata only works with TE

---

src/utils/records.ts

when a locale is not supported, no results will be returned. it should default to the base language of english
- default records to the base language when a non supported locale is requested

fix: default locale

---

docs/economics/staking/index.md

The current docs seem to imply that slashing is implemented in the solana protocol. They also make assumptions about how slashing should or will be implemented (i.e. slashing takes sol from the delegator's principle).  
Reworded the paragraph on slashing to make it clear slashing is not implemented yet.
Fixes #

Removes the implication that solana has slashing

---

docs/rpc/websocket/slotsUpdatesSubscribe.mdx

Unix timestamps are usually in seconds, but this one is in milliseconds.

Specify slotsUpdatesSubscribe's timestamp unit

---

docs/rpc/http/getTokenAccountBalance.mdx

A small mistake in the response structure of getTokenAccountBalance endpoint in Solana docs.
Fixes #
```id``` field is moved to the root object.

Fix response of getTokenAccountBalance.mdx

---

docs/programs/deploying.md

Currently it is hard to deploy programs. Many people still dont know that --use-rpc makes deploys more reliable and adding priority fees is way more reliable. 
Fixes #
Added an example command which shows of these flags.

Add example command to deploy program guide

---

content/guides/token-extensions/transfer-hook.md

There is a potential security problem when the transfer hook instruction can be called out side of a transfer context. 
This section in the guide addresses this. 
All the examples in program examples repository also have this check now.

Add section for adding an is_transferring check

---

docs/rpc/websocket/signatureSubscribe.mdx

just fixed a typo in `docs/rpc/websocket/signatureSubscribe.mdx`
s/recieved/received

fix typo in signatureSubscribe

---

docs/intro/dev.md

Typo error 
- Corrected a spelling mistake in the documentation.
- Changed 'were' to 'where' in the file located at docs/intro/dev.
Fixes #

docs: Correct spelling mistake from 'were' to 'where' in docs/intro/dev

---

content/guides/advanced/how-to-request-optimal-compute.md
content/guides/advanced/how-to-use-priority-fees.md

there are a few lingering links to the old runtime page
- update the old runtime doc links to point to the update fees page
Note: To not conflict with this PR https://github.com/solana-foundation/developer-content/pull/263#pullrequestreview-2177765297, the runtime link in the compression doc was not updated in this PR

[docs] fix runtime docs link

---

content/courses/onchain-development/local-setup.md
content/guides/getstarted/setup-local-development.md
content/guides/getstarted/solana-test-validator.md
docs/intro/dev.md

The old install url points to solana.com, which has 1.17.x as stable version, we want people to use the newest stable version. Since the anza docs are not yet published this is a quick fix to reach some of the developers earlier. 
Just a search and replace

Replace solana.com cli install url with anza.xyz

---

docs/advanced/lookup-tables.md

Motivated by https://github.com/anza-xyz/agave/issues/2194
The Agave validator client has a cap of 64 locks (read or write) per transaction, which means that you can only have 64 unique accounts in a transaction. A transaction with >64 accounts will throw a `TooManyAccountLocks` error. 
[Example Explorer link from the above issue
](https://explorer.solana.com/tx/inspector?signatures=%255B%25221111111111111111111111111111111111111111111111111111111111111111%2522%255D&message=gAEABhTWF9K8PuztHUzAf2mtX5gzqQC5i%252BP%252FcOdB0hEyPbIQ4wIiP%252B2OepTpOyUxVepz9I5ExjZ6uZG2VM8exG3yQ%252BOTCgUkQaFYTleMcAX2p74eBXQZd1dwDyQZAPJfSv2KGc4yFBMogxxTU%252BU%252BGrhwhIBuhLAUJKe6Zau3pURqgPmu7FA%252FgvuGgmnoWJEPG2j2y0CyJx28Eq1SQH9FGXq3TGZYXfhaYt2vwu8t4GKm7%252BXhW6FzNqbD7OWi46ncjnr5bQezTPFjMwHVVIvZ0d3TADZPigtzI …

Change lookup-tables to clarify only 64 addresses in a single transaction

---

contentlayer.config.ts
docs/index.md
docs/rpc.md
docs/terminology.md
src/app/api/content/[...slug]/route.ts
src/types/index.ts
src/utils/navItem.ts

Skip rpc and terminology pages when setting next/previous page routes
- `/doc` now skips over rpc and terminology page on next navigation
- `/docs/terminology` now skips rpc page on previous navigation

Skip rpc and terminology pages when setting next/previous page routes

---

content/courses/onchain-development/intro-to-anchor.md

The ordering of the steps on the lab section is not ideal
Changed the ordering of the steps to represent, in order, the following:
- Account type declaration
- Context declaration
- Instruction handler using the previously declared account and context

Changed step order of lab section

---

CONTRIBUTING.md
content/courses/token-extensions/cpi-guard.md
content/courses/token-extensions/group-member.md
content/courses/token-extensions/immutable-owner.md
content/courses/token-extensions/interest-bearing-token.md
content/courses/token-extensions/permanent-delegate.md
content/courses/token-extensions/required-memo.md
content/courses/token-extensions/token-extensions-in-the-client.md
content/courses/token-extensions/token-extensions-onchain.md
content/courses/token-extensions/transfer-hook.md

This is the content from https://github.com/Unboxed-Software/solana-course/pull/375 - Unboxed final PR for their Token Extensions work. 
- Lessons are added to the `token-extensions` course
- Descriptions are added, headers are adjusted to start from h2
That PR included some changes to other files (I asked unboxed to do those in a separate PR but oh well), but it mostly seems to be fixes we've already applied - see https://github.com/solana-foundation/developer-content/pull/301

Add new token extensions lessons from Unboxed

---

content/courses/offline-transactions/durable-nonces.md
content/courses/offline-transactions/metadata.yml

I was doing an audit of Unboxed's final Token Extensions PRs, making sure everything is in `developer-content` before we archive `unboxed-software/course`, and I realised we missed including the durable nonce lesson in a course. Previously it was just in a vague 'advanced' module. 
This PR makes a single 'offline transactions' course with `durable-nonces` as a single lesson.

Add durable-nonces from Unboxed repo

---

content/cookbook/development/connect-environment.md
content/cookbook/development/index.md
content/cookbook/development/start-local-validator.md
content/cookbook/development/subscribing-events.md
content/cookbook/development/test-sol.md
content/cookbook/development/using-mainnet-accounts-programs.md

from: https://solanacookbook.com/references/local-development.html#starting-a-local-validator
to: https://solana.com/developers/cookbook/development/start-local-validator

migrate local development refs from cookbook

---

content/courses/tokens-and-nfts/nfts-with-metaplex.md

Addresses #326. Solana DevRel did discuss moving everything to Umi, but the feeling was that the complexity of Umi hurts the developer experience and there may be better long-term solutions once web3.js v2 is released.

Add note re: recent Metaplex JS SDK deprecation.

---

docs/advanced/confirmation.md

The documentation lacked a complete description of the transaction message structure, omitting the header component. This could lead to misunderstanding among developers about the full composition of Solana transactions.
- Added "header with metadata about the transaction" to the list of transaction message components
- Updated the transaction lifecycle description to include the creation of the header
Fixes #
This change provides a more accurate and complete description of Solana transaction structure, which should help developers better understand how transactions are composed and processed.

Add header to transaction component description in docs

---

README.md
content/courses/connecting-to-offchain-data/metadata.yml
content/courses/native-onchain-development/metadata.yml
contentlayer.config.ts
src/types/index.ts

This adds an `isHidden` field to courses, and hides `native-onchain-development` and `connecting-to-offchain-data`  while we get a CFP together to update them.  
Other minor fixes: add `courses` to the content types mentioned in the README.
Note there is a second PR for solana-com repo https://github.com/solana-foundation/solana-com/pull/15 to use this field.

Add isHidden to courses and hide outdated Unboxed courses

---

docs/advanced/actions.md

it is unclear that action api responses should use the same action error
moved the action error details to a dedicated section and added amplifying info

[docs] clarify action errors

---

.vscode/extensions.json
CONTRIBUTING.md

There's an existing [CONTRIBUTING.md](https://github.com/Unboxed-Software/solana-course/blob/main/CONTRIBUTING.md) used by the Unboxed Course, created by James and I, and used for both the Unboxed Course and Professional Education programs. Per Slack, ideally we could delete 90% of it and just refer to the one in this repo, with some added bits.

Add prose, JS/TS & Rust guidelines used by Unboxed and prof-education

---

docs/rpc/deprecated/confirmTransaction.mdx
docs/rpc/deprecated/getFeeRateGovernor.mdx
docs/rpc/deprecated/getSignatureConfirmation.mdx
docs/rpc/deprecated/getSignatureStatus.mdx
docs/rpc/deprecated/getStakeActivation.mdx

Update docs deprecated rpc methods pages to match the [Agave v2.0 Transition Guide](https://github.com/anza-xyz/agave/wiki/Agave-v2.0-Transition-Guide#step-2-review-removed-rpc-endpoints-and-sdk-elements).
- Moved `getStakeActivation` page to deprecated section
- Added recommended alternative to `getFeeRateGovernor` page
- Added pages to deprecated section for `confirmTransaction`, `getSignatureStatus`, `getSignatureConfirmation`. 
Just adding these pages as placeholders to point to recommended v2 alternatives.
The code example `curl` commands for deprecated methods already return "Method not found" on devnet endpoint:
```
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}
```
However, I'm not entirely sure what `getSignatureConfirmation` refers to. 
Assuming …

Update deprecated rpc methods

---

content/courses/program-security/security-intro.md

The hyperlinks to the Anchor and native Rust programs were incorrect or duplicated.
- Updated hyperlinks for the Anchor and native Rust programs to ensure they point to the correct courses.

security-intro.md - fix: hyperlinks to courses

---

content/courses/program-security/duplicate-mutable-accounts.md

Updated a lesson compatible with the latest anchor version, conventions, and best practices as per the guidelines and fixed grammatical mistakes.
Unboxed PRs
Starter - https://github.com/Unboxed-Software/solana-duplicate-mutable-accounts/pull/1
Solution - https://github.com/Unboxed-Software/solana-duplicate-mutable-accounts/pull/2
Fixes #

Program Security - Updated duplicate mutable accounts lesson 

---

content/courses/onchain-development/anchor-pdas.md

There were some typos in the documentation.
"not" and "initializing" were misspelled
"initalization" -> "initialization"
"bot" -> "not"

Found and Fixed some typos while reading the documentation

---

content/guides/dapps/cash-app.md

This commit corrects a typo in a code reference where a single '=' was  used instead of '==':
`require!(cash_account.owner = ctx.accounts.signer, ErrorCode::InvalidSigner);`
Contrary to the actual code implementation:
`require!(cash_account.owner == ctx.accounts.signer.key(), ErrorCode::InvalidSigner);`
This fix ensures the example or documentation accurately reflects the intended comparison logic, avoiding confusion for developers referencing this code.
Fixes #

Fix typo in code reference: missing  an other '='.

---

docs/rpc/http/getRecentPerformanceSamples.mdx

The docs for the `getRecentPerformanceSamples` method include a return field of `numNonVoteTransaction`. The correct field is `numNonVoteTransactions` (with an "s").
The error also currently exists in the `solana-web3.js` repo, see https://github.com/solana-labs/solana-web3.js/pull/3202
You can confirm the correct fields with:
```sh
curl https://api.devnet.solana.com -X POST -H "Content-Type: application/json" -s \
-d '{"jsonrpc":"2.0", "id":1,"method": "getRecentPerformanceSamples","params": [1]}'
```
Returns..
```js
{
"jsonrpc": "2.0",
"result": [
{
"numNonVoteTransactions": 850,  // <--- 👀
"numSlots": 163,
"numTransactions": 2792,
"samplePeriodSecs": 60,
"slot": 323584907
}
],
"id": 1
}
````
Fixing misnamed field in the return data for the `getRecentPerformanceSamples` method.

Fixing misnamed field in `getRecentPerformanceSamples` return data

---

content/courses/native-onchain-development/serialize-instruction-data-frontend.md
content/guides/games/energy-system.md

- The code for fetching and managing player data had inconsistent use of .then() for handling promises.
- Error handling was not robust, leading to potential issues if data fetching or decoding fails.
- Account change subscription lacked proper cleanup, which could cause memory leaks.
- Refactored code to use async/await for consistency and readability.
- Added try/catch blocks for improved error handling when fetching and decoding player data.
- Created a separate async function for fetching player data to enhance code organization.
- Implemented error handling in the account change callback to handle decoding errors.
- Added cleanup logic for the account change subscription to prevent memory leaks.

Refactor/energy system (serialize-instruction-data-frontend.md)

---

content/courses/onchain-development/anchor-pdas.md

Commit 14155b1ffd7341edd4190a77cfe142b05e7c7b00 introduced a typo in the 
`anchor_movie_review_program` making the code unable to compile.
Replace `MovieAccountState::INIT_SOACE` by `MovieAccountState::INIT_SPACE`

Fix INIT_SPACE typo

---

docs/intro/installation.md

- Add recommendation to change rust version to <1.80 if encounter `error[E0282]: type annotations needed for Box<_>`
https://github.com/coral-xyz/anchor/pull/3143
- Add recommended solution if solana platform tool installation fails and causes `error: not a directory:`
https://solana.stackexchange.com/questions/13174/anchor-build-fail-due-to-no-platform-tools-rust-lib

Update installation page to include solution to common install error

---

docs/intro/installation.md

the installation page has render errors due to some odd crowdin parsing
fix the formatting
note: https://github.com/solana-foundation/solana-com/pull/37 is already live to also support this PR and fixes
Fixes #455, #396, #381

fix: render error on install page

---

content/courses/onchain-development/anchor-pdas.md

Fix UpdateMovieReview struct: Add missing comma in account attribute
The UpdateMovieReview struct in the movie review system contained a syntax error in the #[account] attribute macro. A missing comma after the 'realloc' parameter caused the following compiler error:
```shell
error: expected non-macro attribute, found attribute macro `account`
```
This error prevented the code from compiling and blocked the proper functioning of the movie review update process.
Added a missing comma in the #[account] attribute macro of the UpdateMovieReview struct, specifically after the 'realloc' parameter. This ensures all parameters within the attribute are properly separated.
Fixes 
Resolves the compiler error by correcting the syntax in the #[account] attribute.
-Allows the code to compile …

Fix syntax error in UpdateMovieReview struct: Add missing comma after realloc attribute

---

content/courses/native-onchain-development/program-state-management.md

- Updated content as per given guidelines.
- Updated styling and grammar fixes
- Updated code snippets with latest Rust and solana program 
- Updated program code and updated link 
Fixes #
Updated program code - https://beta.solpg.io/66d67458cffcf4b13384d331

Native onchain development - Updated program state management lesson

---

content/courses/onchain-development/anchor-pdas.md

PDAs store data, at addressed specified by the onchain programmer, using a list of seeds, a bump seed, and a program ID.
Addressed should instead be "addresses".
Changed "addressed" to "addresses"

Fix a typo in anchor-pdas.md

---

CONTRIBUTING.md

Old link is dead, updated with new location.
Clicking the existing link for Multiple Files Template in CONTRIBUTING.md leads to a 404 page in Anchor's docs. 
Searched for Multiple Files Template in Anchor's docs, found the only link that seemed to have relevant data, and updated existing CONTRIBUTING.md Anchor Multiple Files Template link with the working link. 
Fixes #

Edit: link: Anchor Multiple Files Template

---

content/courses/native-onchain-development/program-derived-addresses.md

Part of the `superteam-lesson-updates`
The lesson on program derived addresses needs some updates to show the uses of the 3 methods on the `Pubkey` that are used to derive  a PDA.
Token Extensions was standardized but not updated in this repository.
The content also contains a lot of grammatical errors.
1. Rewrote  sentences and correct grammatical mistakes found using grammarly
2. The `get_associated_token_address_with_program_id` function is used to show how ATAs are derived using the Token Extensions program ID
3. Informs a user on when to use the methods of `Pubkey` to find ATAs
Fixes #
- Correct the grammatical errors that were found using grammarly
- Inform the user when to use the methods:
- find_program_address
- try_find_program_address
- create_program_address - for perfomant …

Improves the program derived addresses content

---

content/courses/offline-transactions/durable-nonces.md

- Updated code snippets
- Use Partial signing for transactions with multiple signers.
- Use `getExplorerLink` from solana-helpers for easier link generation.
- Added the calculation for the exact rent-exempt balance using `connection.getMinimumBalanceForRentExemption`.
- Added screenshots of successful test runs are included in the documentation.
- Fixed grammar and styling
- Fixed as per guidelines
Fixes #
Unboxed PRs
https://github.com/Unboxed-Software/solana-lab-durable-nonces/pull/1

Update Durable Nonces Course

---

content/courses/program-optimization/rust-macros.md

The rust-macros.md file contains grammatical errors, outdated dependencies, legacy way to find space of a type in anchor program, broken links and missing repository for starter code.
- Fixes for grammatical errors via grammarly recommendations
- New repository to replace the missing Unbox Software repository linked to by the article 
https://github.com/448-OG/anchor-custom-macro
-  Upgraded dependencies
Fixes #
- eprintln now uses `()` instead of `{}` since eprintln is a macro defined as standard in Rust therefore using `()` follows common Rust patterns
- Use `LitStr::token()` since current version of `syn` crate does not print the whole token structure in fmt::Debug. Using `token()` returns a literal which better shows the internal representation of a LitStr and the `extra-traits` must …

Improvements and fixes for the rust-macros.md file

---

CONTRIBUTING.md

Lines 78 - 80 of CONTRIBUTING.md state: 
Use apostrophes of possession,
[including for inanimate objects](https://english.stackexchange.com/questions/1031/is-using-the-possessive-s-correct-in-the-cars-antenna).
Eg 'the account's balance' is correct.
_But_ lines 87 - 88 seem to be missing the possessive apostrophe for "functions handler."
Add possessive apostrophe for "function's handler," assuming that functions in Anchor are defined in a way that specifies how to handle the instructions sent from clients. However, I am not certain that I am interpreting the documentation accurately, and the existing "functions handler" might be contextually accurate.  
Maybe it would be clearer to say something like, "The `multiple files template` in Anchor also calls each defined function's respective …

Add apostrophe to inanimate possessive object

---

docs/advanced/confirmation.md

There is a missing backtick (`) in order to correctly format the link.
Add the missing backtick (`) at the end of the text to correctly format the link.
Fixes #

fix: typo with getMaxShredInsertSlot link

---

content/courses/onchain-development/intro-to-anchor-frontend.md

"build" is the command to build a project, but the correct tense in the context of that sentence would be "built"
replace "build" with "built" for grammatical clarity. 
Fixes #

Fix a single typo

---

content/courses/intro-to-solana/getting-started.md
content/courses/intro-to-solana/intro-to-cryptography.md
content/courses/intro-to-solana/intro-to-writing-data.md

1.  As was specified in the guide, no headings should end with any special characters (i.e. `:;!@#$%^&*`).
2. And there should be a `sentence/paragraph` between two headings.
There are a couple of issues in that portion from courses/intro-to-solana
Changed the contents of `.md` files from `courses/intro-to-solana`
1. `## Welcome!` to `## Welcome`
2. `### Experiment!` to `### Experiment`
3. Have put a sentence relatable in between two headings.
Fixes #
1. Removed `:;!@#$%^&*` from headings.

Intro to solana content

---

docs/rpc/http/getTokenAccountsByOwner.mdx

https://github.com/solana-foundation/developer-content/issues/520
updated that the second param is also required per the [RPC source](https://github.com/anza-xyz/agave/blob/c7283625a9efa64377597e7e098a0f9965ff259a/rpc/src/rpc.rs#L2490-L2516)
Fixes #520

[docs/rpc] fix: required field on `getTokenAccountsByOwner`

---

content/courses/intro-to-solana/intro-to-custom-onchain-programs.md

Here https://solana.com/developers/courses/intro-to-solana/intro-to-custom-onchain-programs#instructions, it's mentioned that in previous chapters, we used the below functions:
- SystemProgram.transfer()
- mintTo() and transfer()
- createCreateMetadataAccountV3Instruction()
This is incorrect. I've read and checked out the previous chapters. Only SystemProgram.transfer() is used. The other two functions haven't been used/introduced yet.
Removed the irrelevant lines that could confuse the reader.
Fixes #545

Fix inconsistency in intro-to-custom-onchain-programs.md

---

content/courses/solana-pay/solana-pay.md

- Changed `fromPubkey: account` to `fromPubkey: new PublicKey(account)` to ensure proper handling of the public key.
Using `new PublicKey(account)` ensures that the account variable is properly converted to a PublicKey instance, preventing potential issues with the transfer instruction.

Updated fromPubkey to use PublicKey in the transfer instruction

---

docs/intro/dev.md

While `solanaKT` is a great library, there are many reasons why we might want to add alternatives. Let me list a couple:
- `sol4k` is a well-maintained library with frequent releases and convenient APIs similar to those of `web3.js`
- it is up to date with the Solana updates (for instance, it supports versioned transactions) 
- widely used in the Kotlin community (projects like [web3auth](https://web3auth.io/docs/connect-blockchain/solana/android) or [Mixin Network](https://github.com/MixinNetwork/android-app) among others)
- it is built not only for Android but also for back-end development with Kotlin or Java (no Android-specific dependencies, no need to import the `jetpack` repository, etc.) 
- it is simplistic and lightweight (no heavy-weight dependencies like `bitcoinj`)
Adds …

Add sol4k to the client-side development section

---

content/courses/onchain-development/intro-to-anchor-frontend.md

There is a typo in the documentation where "species" is used instead of "specifies". This incorrect word usage could lead to confusion for readers.
The word "species" has been changed to "specifies" to correct the typo and improve clarity.
Fixes #

Fix typo: Change "species" to "specifies" in documentation

---

content/courses/program-optimization/lookup-tables.md

Update the Address Lookup Tables (LUTs) course to comply with the SoLana contributing guide.
- Simplified explanations of versioned transactions and Address Lookup Tables (LUTs).
- Updated code examples to align with best practices.
- Ensured the documentation followed the guidelines from the Solana contributing guide.
- Enhance readability
Unboxed PR
https://github.com/Unboxed-Software/solana-versioned-transactions/pull/1

Update Lookup Tables (LUTs) course

---

content/courses/token-extensions/close-mint.md
content/courses/tokens-and-nfts/token-program.md

TERMINOLOGY "mint" is not proper in the context "In this lab, we'll create a mint with the close mint extension.".
missing typescript code example for using an account on devnet while calling "initializeKeypair" in the section [2. Run validator node]
missing typescript code example for importing our
new function in the section [3. Create a mint with close authority]
"mintInfo" is redeclared in the typescript.
change "mint" to "token mint account".
add a typescript code example for using an account on devnet while calling "initializeKeypair" in the section [2. Run validator node]
add a typescript code example for importing our new function in the section [3. Create a mint with close authority]
change "const mintInfo" to "let mintInfo" because "mintInfo" is used again in the "CLOSE MINT" …

fix and improve close-mint course

---

content/courses/onchain-development/anchor-pdas.md

Added argument checks to update movie review function in order to display user-friendly error message.
Remove description argument passed to AddMovieReview and UpdateMovieReview instruction macro as it is not used in the Accounts struct.

Added argument checks - for better error display.

---

docs/intro/quick-start/program-derived-address.md

The description for the delete logic should be: implement the logic for the 'delete' instruction rather than  ...  'update' instruction
The description for the delete logic should be modified.
--->> implement the logic for the 'delete' instruction rather than implement the logic for the  'update' instruction
Fixes #

Fix a typo for the 'delete' instruction

---

content/courses/tokens-and-nfts/token-program.md

no try/catch for async/await calls, which is not following CONTRIBUTING.md.
[Token Extensions Program] link is wrong.
[add a second account on devnet] link is wrong.
wrong ts command in the section [Create an Associated Token Account to store the tokens].
console.log displays a wrong explorer link due to "!".
add try/catch for async/await calls following CONTRIBUTING.md.
delete unnecessary "!" for generating a wrong explorer link.
add some missing instructions.
fix a wrong ts command for the section [Create an Associated Token Account to store the tokens].

fix and improve token-program course

---

content/courses/mobile/mwa-deep-dive.md

There were broken links and terminology that didn't appear to follow contributing guidelines.
1. Contributing guide recommends using  'secret key' rather than 'private key'
2. Contributing guide recommends 'blockchain' or 'web3' rather than 'crypto'.
3. Added the `.md` file extension to broken links. 
Note: I linked the solution code to the [Unboxed Software](https://github.com/Unboxed-Software/react-native-fake-solana-wallet/tree/solution) repo, though I'm not sure if this was the right link. Let me know if this needs fixing.

 Fix broken links and terminology in mwa-deep-dive.md

---

tsconfig.json

recent code-import pr prevents building the nextjs app due to nextjs attempting to validate the types included in any of the code files stored in the `code` dir
ignore the `code` dir via tsconfig

fix: exclude code dir

---

content/courses/mobile/intro-to-solana-mobile.md
content/courses/mobile/solana-mobile-dapps-with-expo.md

1. Fixed broken links
2. Suggested rewording: changed "prerequisites" to "Getting Started" because the original Prerequisites section in the [Introduction to Solana Mobile](https://github.com/solana-foundation/developer-content/blob/main/content/courses/mobile/intro-to-solana-mobile.md) lesson was deleted and renamed to "Getting Started" in a recent PR update and would make it easier for beginners to find/navigate to.
3. Adjust grammar and wording to make it a little more concise.
4. The Auth Provider link was recently changed in another PR but the link was broken, I changed it to what [looks like the correct link](https://raw.githubusercontent.com/solana-developers/mobile-apps-with-expo/main/components/AuthProvider.tsx), but not sure if this is the intended link. Let me know if this …

Fix broken links in solana-mobile-dapps-with-expo.md

---

CONTRIBUTING.md

the link no longer works; further research shows LTex is a sub-par alternative users don't enjoy, but I'm not sure if there are any other options for VSCode users. 
https://www.reddit.com/r/vscode/comments/1crtdg8/grammarly_extension_removed/
Remove dead link.
Fixes #

Remove deprecated link to nonexistent VSCode Grammarly extension

---

content/courses/state-compression/generalized-state-compression.md
docs/programs/anchor/index.md
docs/programs/deploying.md
docs/programs/faq.md
docs/programs/lang-rust.md
docs/programs/limitations.md

Add back the following pages, with minor updates to remove references to removed C page:
- /docs/programs/faq
- /docs/programs/lang-rust
- /docs/programs/limitations

Add back lang-rust, limitation, faq pages under programs section

---

docs/intro/installation.md

The section about the problem mentioned in https://github.com/coral-xyz/anchor/pull/3143 is now resolved (https://github.com/coral-xyz/anchor/pull/3315), which made the following section redundant:
https://github.com/solana-foundation/developer-content/blob/74cc35d3de8975e2e7731089b864bcb0377a16d6/docs/intro/installation.md#L366-L400
Remove all references to Rust 1.79.0 installation from the Anchor installation section.

Remove Rust 1.79.0 section from Anchor installation

---

docs/intro/dev.md

LMAX have recently open sourced a new Java SDK. It should be on the list of supported Java SDKs within the documentation.  On a quick comparison between `solana4j` (LMAX's) and `solanaj` (skynetcap's), `solana4j` looks _at least_ as complete, if not more complete. Please note, I work for LMAX and I was responsible for open sourcing it.
Adds a link to LMAX's solana4j library within the documentation, a recently open sourced Java SDK for Solana. 
Fixes #
N/A

Add solana4j (open sourced by LMAX) to the list of client-side java sdks

---

content/guides/advanced/introduction-to-durable-nonces.md

correct difficulty to match slug, corrected typo, changed to official faucet, fixed heading (in MD if 2 headings have the same name, the anchor tag will point to first link
typo fix Displace to Display
make headings unique = Create Nonce Account / Create Nonce Authority
updated faucet to official Solana 
changed difficulty to Advanced
Fixes #

Minor changes and fixes to Intro to Durable Nonces

---

content/guides/advanced/stake-weighted-qos.md

The QUIC tpu port number was incorrectly listed in the docs. This change tells the user to get the
QUIC tpu port from the getClusterNodes RPC call.
The QUIC tpu port number was incorrectly listed in the docs
Suggest the use of getClusterNodes RPC call
Fixes #

Fixed SW QoS doc to use getClusterNodes

---

content/courses/onchain-development/intro-to-anchor-frontend.md

In one of the [examples](https://github.com/solana-foundation/developer-content/blob/c050fd3b48e53b8a896e852b7555ecdd2a4cb53a/content/courses/onchain-development/intro-to-anchor-frontend.md?plain=1#L417C1-L420C78) , there was a type error: 
caused by conversion of `Program<Idl>` to `Program<CounterProgram>`
Change to direct conversion when passing `idl` to `Program`

Fix: resolve type error in program initialization example

---

content/courses/onchain-development/anchor-cpi.md

in this page https://solana.com/developers/courses/onchain-development/anchor-cpi
if you run `anchor test` in the final example, you can see errors:
```
"Program log: Instruction: MintTo",
"Program log: Error: owner does not match",
```
the reason is in this line:
https://github.com/solana-foundation/developer-content/blob/5dc01dd84e01f5dfcb7b0cb7947c3a533e73bba7/content/courses/onchain-development/anchor-cpi.md?plain=1#L555
it passed an incorrect mint authority, because in `InitializeMint`, the `authority` passed with `user`, which is the signer. but when it call `MintTo` in `CpiContext::new_with_signer`,  `authority` is incorrectly passed as `mint`. which is not the authority of itself, instead  the signer, `ctx.accounts.initializer.to_account_info()`, should be passed in.
Fixes #
Also …

fix: mint authority

---

content/courses/onchain-development/anchor-cpi.md

While I was reviewing #571
- Fix circular 'remaining accounts' definition
- signer_seeds is for multiple signers, not just one
- Grammarly fixes

Small fixes to Anchor CPI

---

content/cookbook/accounts/close-account.md

Close Accounts example reflects a potential exploit by not reassigning account ownership (thank you to Sec3 for flagging this). This is shown by the Anchor Sealevel attack example https://github.com/coral-xyz/sealevel-attacks/blob/master/programs/9-closing-accounts/insecure-still/src/lib.rs
Reassign and realloc the account so ownership of an unclosed account cannot be faked.
Fixes #

Update Close Account to reflect best practices.

---

docs/intro/dev.md

C# and gd script sdks were missing from the list of client SDKs
Added links to these SDKs

Add links to C# and gdscript sdks

---

content/courses/intro-to-solana/intro-to-cryptography.md
content/courses/intro-to-solana/intro-to-reading-data.md
content/courses/native-onchain-development/cross-program-invocations.md
content/courses/state-compression/compressed-nfts.md
content/courses/token-extensions/close-mint.md
content/courses/token-extensions/default-account-state.md
content/courses/token-extensions/immutable-owner.md
content/courses/token-extensions/interest-bearing-token.md
content/courses/token-extensions/non-transferable-token.md
content/courses/token-extensions/permanent-delegate.md
content/courses/token-extensions/required-memo.md
content/courses/token-extensions/transfer-fee.md
content/courses/tokens-and-nfts/nfts-with-metaplex.md
content/courses/tokens-and-nfts/token-program.md
content/guides/getstarted/full-stack-solana-development.md
content/guides/getstarted/local-rust-hello-world.md
content/guides/javascript/compressed-nfts.md
content/guides/wallets/add-solana-wallet-adapter-to-nextjs.md
docs/clients/javascript.md

Read why, here: https://github.com/solana-labs/solana-web3.js/issues/3498

Lock web3.js to version 1.x for compatibility

---

content/cookbook/development/subscribing-events.md
content/courses/native-onchain-development/deserialize-custom-data-frontend.md
content/guides/advanced/introduction-to-durable-nonces.md
content/guides/dapps/cash-app.md
content/guides/getstarted/intro-to-native-rust.md
content/guides/getstarted/solana-token-airdrop-and-faucets.md
content/guides/javascript/compressed-nfts.md
content/guides/javascript/get-program-accounts.md
docs/advanced/actions.md
docs/advanced/lookup-tables.md
docs/advanced/state-compression.md
docs/advanced/versions.md
docs/clients/javascript-reference.md
docs/clients/javascript.md
docs/core/fees.md

GitHub Pages doesn't offer 301 redirects. These URLs changed.
Regex'd this: `solana-labs.github.io/solana-web3.js/([^\)]+)`
Replaced with: `solana-labs.github.io/solana-web3.js/v1.x/$1`

Update `@solana/web3.js` documentation URLs to point at new `v1.x` folder

---

docs/programs/anchor/idl.md

Missing documentation on the events discriminator composition/computation
https://solana.com/docs/programs/anchor/idl#discriminators
Added the missing documentation looking at the documentation on accounts discriminators

Adding documentation for events discriminator

---

content/guides/advanced/verified-builds.md

During my tests i noticed there needs to be different Cargo.toml configurations depending on where in the repository the program is located. 
Added Cargo.toml explanation 
Added two examples projects from Solana developers 
Added Docker image verification 
Fixed typos

Add cargo.toml explanation and example programs

---

docs/core/clusters.md

added high level examples and a table

---

content/courses/tokens-and-nfts/nfts-with-metaplex.md

Correct the mismatched program name.
Correct the mismatched program name.
before
- `create-metaplex-nft-collection.ts` / `create-metaplex-collection.ts` two separate names
tobe
- delete `create-metaplex-collection.ts`
Fixes #

fix nfts with metaplex code name

---

content/cookbook/accounts/calculate-rent.md
content/cookbook/accounts/create-account.md
content/cookbook/accounts/get-account-balance.md
content/courses/tokens-and-nfts/nfts-with-metaplex.md
docs/core/clusters.md

added several cookbook examples

Cookbook v2 snippets

---

content/cookbook/wallets/check-publickey.md

Solana Web3.js v2 example for checking if address is valid on curve, valid off curve and invalid
Fixes #

Update check-publickey.md to include web3.js v2 example

---

content/cookbook/development/load-keypair-from-file.md
content/cookbook/transactions/send-sol.md
content/cookbook/wallets/connect-wallet-react.md
content/cookbook/wallets/restore-keypair.md

- fix prettier error
- add link to web3js react example
- use `createKeyPairSignerFromBytes` instead of `createKeyPairFromBytes`
- increase lamports in SOL transfer above minimum rent

minor updates to web3js v2 examples

---

docs/rpc/http/simulateTransaction.mdx

When I was trying the simulate transaction RPC method, I realized that the example had a typo error. 
I removed the typo error.
Fixes #

removing comma which makes JSON example as invalid

---

content/courses/onchain-development/anchor-cpi.md

After implementing the code in the Lab section of the Anchor CPI lesson [here](https://solana.com/developers/courses/onchain-development/anchor-cpi), I ran into the following build errors:
```
% anchor build
Compiling anchor-movie-review-program v0.1.0 (/Users/s/anchor-movie-review-program/programs/anchor-movie-review-program)
Finished release [optimized] target(s) in 1.46s
Compiling anchor-movie-review-program v0.1.0 (/Users/s/anchor-movie-review-program/programs/anchor-movie-review-program)
error[E0599]: no function or associated item named `create_type` found for struct `anchor_spl::token::Mint` in the current scope
--> programs/anchor-movie-review-program/src/lib.rs:89:10
|
89 | #[derive(Accounts)]
|          ^^^^^^^^ function or associated item not found in `Mint`
|
= note: this …
```

Fixing compile error in Anchor CPI lesson

---

content/courses/onchain-development/anchor-cpi.md

Found these small typos while I was going through this lesson. One of the typos in the code snippets was leading to failing tests when running `anchor test` at the end of the lab:
```
anchor-movie-review-program
✔ Initializes the reward token (271ms)
1) Movie review is added
2) Movie review is updated
3) Movie review is deleted
1 passing (305ms)
3 failing
1) anchor-movie-review-program
Movie review is added:
Simulation failed. 
Message: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x4. 
Logs: 
[
"Program log: Title: Test Movie",
"Program log: Description: This was a very good movie.",
"Program log: Rating: 5",
"Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]",
"Program log: Instruction: MintTo",
"Program log: Error: owner does not …
```

Small typos in anchor-cpi.md leading to failing tests

---

content/courses/intro-to-solana/intro-to-custom-onchain-programs.md

I found a typo in the code example. The address constants should be strings, as the keys are declared using them below.
Change the address constants to string type.
Fixes #

fix typo in intro-to-custom-onchain-programs.md

---

docs/core/pda.md

Sometimes we need to be quite explicit with wording in order to make ourselves 100% clear.
In that context _**for**_ leaves a bit of confusion of what we really want to express. That's why I propose to replace _**for**_ with  _**on behalf of**_ ...
replace **_for_** with **_on behalf of ..._**  in order to express more clarity

chore(documentation): PDA's keypoints

---

content/courses/program-optimization/program-architecture.md

In this page: 
https://solana.com/developers/courses/program-optimization/program-architecture
I mainly made 2 small changes:
1.  Remove `cd` from  **test -** `cd tests/sizes.ts`. because here it's meant to indicate the location of the test file, not a `cd` command to execute.
2. Add hyper link to https://mochajs.org/#exclusive-tests on how to add `.only` to the `describe` call, which can be helpful for anyone who hasn't used this feature before.

Trivial fixes

---

docs/advanced/actions.md
docs/advanced/confirmation.md
docs/advanced/lookup-tables.md
docs/advanced/retry.md
docs/advanced/state-compression.md

Typos and grammar and spelling errors around docs files.
Fixed critical inaccuracies and enhanced readability of the documentation to ensure better understanding by developers.
Fixes #

Update docs for higher accuracy and quality of information

---

content/courses/program-security/signer-auth.md

Typo in [Signer Auth lesson](https://solana.com/developers/courses/program-security/signer-auth)
No changes in code, just a simple text change to fix a typo.

Small typo in signer-auth.md

---

content/courses/connecting-to-offchain-data/oracles.md
content/courses/connecting-to-offchain-data/verifiable-randomness-functions.md

fix: readme typos

---

docs/intro/installation.md

The docs read "The RPC URL and Websocket URL specific the Solana cluster the CLI will make". That's a typo if I'm not mistaken. 
Change "specific" to "specify"

Fix typo in installation.md

---

docs/programs/anchor/index.md

The project name is not consistent within the instructions, it refers to `my-program` or `my-project`
Update all references to point to `my-project`

Fix wrong project name, `my-project` instead of `my-program`

---

docs/programs/deploying.md

The long subcommands in single backticks present odd on mobile.
Tweaked the wording to shorten the inline backtick code to make them look better on mobile

refactor: tweak docs

---

README.md
content/cookbook/transactions/send-sol.md
content/courses/native-onchain-development/program-security.md
content/courses/offline-transactions/durable-nonces.md
content/guides/advanced/introduction-to-durable-nonces.md
content/guides/getstarted/local-rust-hello-world.md
content/guides/getstarted/rust-to-solana.md
docs/advanced/confirmation.md
docs/advanced/lookup-tables.md
docs/advanced/versions.md
docs/core/accounts.md
docs/core/fees.md
docs/core/tokens.md
docs/economics/staking/index.md
docs/economics/staking/stake-accounts.md
docs/index.md
docs/intro/dev.md
docs/intro/installation.md
docs/intro/wallets.md
docs/more/exchange.md
docs/programs/testing.md
docs/terminology.md
next.config.js
redirects.json
src/components/HomeComponent.tsx

The old Solana Labs docs site has been shutdown. The Agave validator client docs are now on the Anza docs domains
- updated references to the SolanaLabs docs site in favor of Anza's
- minor updates to bits of copy
- added a missing redirect that was found: `/cluster/economics`

docs: update anza docs links

---

docs/intro/quick-start/program-derived-address.md

fix typo in program-derived-address.md

---

content/courses/native-onchain-development/deserialize-custom-data-frontend.md
content/courses/onchain-development/intro-to-onchain.md
content/courses/program-security/account-data-matching.md
content/courses/program-security/reinitialization-attacks.md
content/courses/tokens-and-nfts/nfts-with-metaplex.md

assorted minor typo fixes and formatting

Assorted fixes

---

content/courses/onchain-development/anchor-cpi.md

Fix confusing XOR operator when exponentiation was meant

---

content/courses/token-extensions/default-account-state.md

remove transfer fee mention mentioned in default account state extension
update to correct extension being thought.

fix: correct slight mixup of transfer fee and default acc state ext
